const $=x=>document.getElementById(x),FMT=new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}),NUM=new Intl.NumberFormat('de-DE',{maximumFractionDigits:2}),EU=x=>Number.isFinite(x)?FMT.format(x):'–',PC=x=>Number.isFinite(x)?NUM.format(x)+' %':'–';
const GR={BW:5,BY:3.5,BE:6,BB:6.5,HB:5.5,HH:5.5,HE:6,MV:6,NI:5,NW:6.5,RP:5,SL:6.5,SN:5.5,ST:5,SH:6.5,TH:5},SN={BW:'Baden-Württemberg',BY:'Bayern',BE:'Berlin',BB:'Brandenburg',HB:'Bremen',HH:'Hamburg',HE:'Hessen',MV:'Mecklenburg-Vorpommern',NI:'Niedersachsen',NW:'Nordrhein-Westfalen',RP:'Rheinland-Pfalz',SL:'Saarland',SN:'Sachsen',ST:'Sachsen-Anhalt',SH:'Schleswig-Holstein',TH:'Thüringen'};
let step=0,importMeta={warnings:[],missing:[],evidence:[]};
const ids=['objectName','location','price','area','rent','otherRent','year','type','occupied','marketRentM2','marketPriceM2','state','grest','notary','broker','reno','furn','specialAssessment','renoTax','nonAlloc','wegReserve','maintM2','admin','vacancy','otherCost','taxMaint','wegFund','futureCapex','futureCapexYear','ltv','loanAmount','interest','repay','fixed','followRate','liquidReserve','tax','building','afaMethod','afa','lossOffset','horizon','target','rentGrowth','costGrowth','priceGrowth','sellCost','taxFreeSale','cRent','cWeg','cTech','cLegal','cMarket','cFinance'];
function n(i){let e=$(i);return !e||e.value===''?NaN:Number(e.value)} function v(i){let e=$(i);return e?e.value:''} function checked(i){return !!($(i)&&$(i).checked)}
function stateData(){let d={};ids.forEach(i=>{let e=$(i);if(!e)return;d[i]=e.type==='checkbox'?e.checked:e.value});return d}
function save(){try{localStorage.setItem('investmentcheck-v2',JSON.stringify({data:stateData(),meta:importMeta}))}catch(e){}}
function load(){try{let x=JSON.parse(localStorage.getItem('investmentcheck-v2')||'{}'),d=x.data||{};ids.forEach(i=>{let e=$(i);if(!e||d[i]===undefined)return;if(e.type==='checkbox')e.checked=!!d[i];else e.value=d[i]});importMeta=x.meta||importMeta}catch(e){}sync()}
function defaultAfa(){let y=n('year');if(!Number.isFinite(y))return;$('afa').value=y>=2023?3:y<1925?2.5:2}
function syncSale(){if(!$('taxFreeSale').dataset.touched){$('taxFreeSale').value=n('horizon')>10?'yes':'no'}} function sync(){let st=v('state');if(st&&GR[st]!=null)$('grest').value=GR[st];if(!$('afa').dataset.touched)defaultAfa();$('afa').disabled=v('afaMethod')==='degressive';syncSale();save()}
function show(s){step=s;document.querySelectorAll('.step').forEach(e=>e.classList.toggle('on',+e.dataset.s===s));$('intro').classList.add('hide');$('prog').classList.remove('hide');$('stxt').textContent=`Schritt ${s} von 7`;$('spct').textContent=Math.round(s/7*100)+' %';$('bar').style.width=(s/7*100)+'%';window.scrollTo(0,0)}
function valid(s){let sec=document.querySelector(`[data-s="${s}"]`),m=[];sec.querySelectorAll('[data-r]').forEach(e=>{if(e.value==='')m.push(e)});let er=$('e'+s);if(er){if(m.length){er.textContent='Bitte die fehlenden Pflichtangaben ergänzen.';er.classList.add('on');m[0].focus();return false}er.classList.remove('on')}return true}
function purchase(price=n('price')){let pct=(n('grest')+n('notary')+n('broker'))/100,closing=price*pct;return{closing,all:price+closing+(n('reno')||0)+(n('furn')||0)+(n('specialAssessment')||0)}}
function annualOwnerCosts(mult=1,price=n('price')){let area=n('area');return ((((n('nonAlloc')||0)+(n('wegReserve')||0)+(n('admin')||0))*12+(n('maintM2')||0)*area+(n('otherCost')||0))*mult)}
function deductibleAnnualCosts(mult=1){let area=n('area');return ((((n('nonAlloc')||0)+(n('admin')||0))*12+(n('taxMaint')||0)+(n('otherCost')||0))*mult)}
function loanInfo(ratePct=n('interest'),price=n('price'),ignoreOverride=false,balanceOverride=null){let override=n('loanAmount'),loan=(!ignoreOverride&&Number.isFinite(override)&&override>0)?override:price*(n('ltv')/100),balance=balanceOverride==null?loan:balanceOverride,pay=balance*((ratePct+n('repay'))/100)/12;return{loan,balance,pay}}
function yearLoan(balance,ratePct,pay){let interest=0,principal=0,i=ratePct/100/12;for(let m=0;m<12;m++){let im=balance*i,pm=Math.min(balance,Math.max(0,pay-im));interest+=im;principal+=pm;balance-=pm;if(balance<=.01){balance=0;break}}return{balance,interest,principal,debtService:interest+principal}}
function irr(cash){let lo=-.999,hi=10;function npv0(r){return cash.reduce((s,c,i)=>s+c/Math.pow(1+r,i),0)}let a=npv0(lo),b=npv0(hi);if(!Number.isFinite(a)||!Number.isFinite(b)||a*b>0)return NaN;for(let k=0;k<120;k++){let mid=(lo+hi)/2,x=npv0(mid);if(Math.abs(x)<.01)return mid;if(a*x<=0){hi=mid;b=x}else{lo=mid;a=x}}return(lo+hi)/2}
function npv(cash,rate){return cash.reduce((s,c,i)=>s+c/Math.pow(1+rate,i),0)}